data_dir: "/path/to/data"
erase: false
api_key_gemini: "your_gemini_api_key"
api_key_mistral: "your_mistral_api_key"
num_workers: 16
neo4j_uri: "neo4j+s://xxxx.databases.neo4j.io"
neo4j_username: "neo4j"
neo4j_password: "your_neo4j_password"
neo4j_database: "neo4j"
pipeline_step: "all"